integration:
  datawarehousereader:
    connectTimeout: 5
    readTimeout: 20
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      datawarehousereader:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
  application:
    name: api-customer
