integration:
  datawarehousereader:
    url: http://datawarehousereader.url
spring:
  main:
    banner-mode: 'off'
  security:
    oauth2:
      client:
        provider:
          datawarehousereader:
            token-uri: http://token.url
        registration:
          datawarehousereader:
            authorization-grant-type: client_credentials
            client-id: the-client-id
            client-secret: the-client-secret
            provider: datawarehousereader
